#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from manifest.toml
ynh_setup_source --dest_dir="$install_dir"
echo "eac2bc6e0cfe6958d61c2925916f0616862b18c23c093508342d373eefa90a3c index.html" > "$install_dir/index.html.sha256"
pushd "$install_dir"
sha256sum --check "index.html.sha256" || ynh_die "The downloaded index.html file is corrupted"
popd

### $install_dir will automatically be initialized with some decent
### permission by default... however, you may need to recursively reapply
### ownership to all files such as after the ynh_setup_source step
chown -R "$app:www-data" "$install_dir"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."


# Create a dedicated NGINX config using the conf/nginx.conf template
ynh_config_add_nginx


#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
