#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers


#=================================================
# REMOVE SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

### This should be a symetric version of what happens in the install script

ynh_config_remove_nginx



#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
